version: "3.8"
services:
  proxy:
    image: proxysql/proxysql
    ports: 
      - 6032:6032  
      - 6033:6033  
    networks: 
      kc_net:
        ipv4_address: 10.0.0.2    
    volumes: 
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
      - ./data/proxydb:/var/lib/proxydb
  mysql:
    image: mariadb:5.5.64
    ports: 
      - 3306:3306
    networks:
      kc_net:
        ipv4_address: 10.0.0.3
    environment:      
      MYSQL_DATABASE: proxy_test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
    volumes: 
      - ./data/mariadb:/var/lib/mysql

networks:
  kc_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.1/24"