version: "3.3"
services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
  fastdfs:
    image: season/fastdfs
    hostname: fastdfs
    container_name: fastdfs
    ports:
      - 22122:22122